// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQCSj6awJaHm_pDrDTbRhqG5QwjHXP76M',
    appId: '1:859634596554:web:9f91c0a607eb3236a19233',
    messagingSenderId: '859634596554',
    projectId: 'expense-tracker-b9e34',
    authDomain: 'expense-tracker-b9e34.firebaseapp.com',
    storageBucket: 'expense-tracker-b9e34.appspot.com',
    measurementId: 'G-YB165YHJJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_m73R_hNeeMa1mCWMvSGXoM1GBAz8NUY',
    appId: '1:859634596554:android:5f1b92609c0cb561a19233',
    messagingSenderId: '859634596554',
    projectId: 'expense-tracker-b9e34',
    storageBucket: 'expense-tracker-b9e34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2C_AuV81DfXxIFd1KkvpBFA3ibMzD7xU',
    appId: '1:859634596554:ios:e1ab9afe99239221a19233',
    messagingSenderId: '859634596554',
    projectId: 'expense-tracker-b9e34',
    storageBucket: 'expense-tracker-b9e34.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2C_AuV81DfXxIFd1KkvpBFA3ibMzD7xU',
    appId: '1:859634596554:ios:e1ab9afe99239221a19233',
    messagingSenderId: '859634596554',
    projectId: 'expense-tracker-b9e34',
    storageBucket: 'expense-tracker-b9e34.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQCSj6awJaHm_pDrDTbRhqG5QwjHXP76M',
    appId: '1:859634596554:web:cf5b6b2bd9111420a19233',
    messagingSenderId: '859634596554',
    projectId: 'expense-tracker-b9e34',
    authDomain: 'expense-tracker-b9e34.firebaseapp.com',
    storageBucket: 'expense-tracker-b9e34.appspot.com',
    measurementId: 'G-Z9FZ9HH0T9',
  );
}
